#!/bin/bash
files_list=$(find "$1" -maxdepth 1 -type f)   #получение списка файлов, находящихся непосредственно во входной директории
all_files_list=$(find "$1" -type f)   #получение списка всех файлов, вложенных во входную директорию
files="$2"
for file in $all_files_list; do   #копирование всех файлов, вложенных во входную директорию, в выходную директорию
    cp "$file" "$files"
done
for file in $all_files_list; do
    base_name=$(basename "$file")
    output_file="$files/$base_name"
    if [ -e "$output_file" ]; then   #присваивание уникального названия файлам, названия которых уже есть в выходной директории
        extension="${base_name##*.}"
        filename="${base_name%.*}"
        unique_filename="${filename}_$(date +%s).$extension"
        cp "$file" "$2/$unique_filename"
    else
        cp "$file" "$2"
    fi
done
